### ISSUE TITLE
[Bug]: Invitation Email is failing with an error

### ISSUE THREAD

**Issue by mknet3** [BerriAI/litellm#10999]
### What happened?

When the invitation email is sent, there is an error in the process to get the invitation link that prevents the email to be sent.

### Relevant log output

```shell
Task exception was never retrieved
future: <Task finished name='Task-83' coro=<UserManagementEventHooks.async_user_created_hook() done, defined at /usr/lib/python3.13/site-packages/litellm/proxy/hooks/user_management_event_hooks.py:33> exception=TypeError("LiteLLM_InvitationLinkActions.find_many() got an unexpected keyword argument 'orderBy'. Did you mean 'order'?")>
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/litellm/proxy/hooks/user_management_event_hooks.py", line 51, in async_user_created_hook
    await UserManagementEventHooks.async_send_user_invitation_email(
    ...<3 lines>...
    )
  File "/usr/lib/python3.13/site-packages/litellm/proxy/hooks/user_management_event_hooks.py", line 122, in async_send_user_invitation_email
    await email_logger.send_user_invitation_email(
        event=event,
    )
  File "/usr/lib/python3.13/site-packages/litellm_enterprise/enterprise_callbacks/send_emails/base_email.py", line 36, in send_user_invitation_email
    email_params = await self._get_email_params(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/lib/python3.13/site-packages/litellm_enterprise/enterprise_callbacks/send_emails/base_email.py", line 125, in _get_email_params
    base_url = await self._get_invitation_link(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        user_id=user_id, base_url=base_url
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/litellm_enterprise/enterprise_callbacks/send_emails/base_email.py", line 190, in _get_invitation_link
    invitation_rows = await prisma_client.db.litellm_invitationlink.find_many(
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        where={"user_id": user_id},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        orderBy={"created_at": "desc"},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: LiteLLM_InvitationLinkActions.find_many() got an unexpected keyword argument 'orderBy'. Did you mean 'order'?
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.70.2-nightly

**Comment by mknet3** [comment]
Related to this issue https://github.com/BerriAI/litellm/issues/10942

**Comment by ishaan-jaff** [comment]
Resolved on main @mknet3

**Comment by mknet3** [comment]
@ishaan-jaff I still see the issue in the latest version ->

```
Task exception was never retrieved
future: <Task finished name='Task-4897' coro=<UserManagementEventHooks.async_user_created_hook() done, defined at /usr/lib/python3.13/site-packages/litellm/proxy/hooks/user_management_event_hooks.py:33> exception=TypeError("LiteLLM_InvitationLinkActions.find_many() got an unexpected keyword argument 'orderBy'. Did you mean 'order'?")>
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/litellm/proxy/hooks/user_management_event_hooks.py", line 51, in async_user_created_hook
    await UserManagementEventHooks.async_send_user_invitation_email(
    ...<3 lines>...
    )
  File "/usr/lib/python3.13/site-packages/litellm/proxy/hooks/user_management_event_hooks.py", line 122, in async_send_user_invitation_email
    await email_logger.send_user_invitation_email(
        event=event,
    )
  File "/usr/lib/python3.13/site-packages/litellm_enterprise/enterprise_callbacks/send_emails/base_email.py", line 36, in send_user_invitation_email
    email_params = await self._get_email_params(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/lib/python3.13/site-packages/litellm_enterprise/enterprise_callbacks/send_emails/base_email.py", line 125, in _get_email_params
    base_url = await self._get_invitation_link(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        user_id=user_id, base_url=base_url
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/litellm_enterprise/enterprise_callbacks/send_emails/base_email.py", line 190, in _get_invitation_link
    invitation_rows = await prisma_client.db.litellm_invitationlink.find_many(
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        where={"user_id": user_id},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        orderBy={"created_at": "desc"},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: LiteLLM_InvitationLinkActions.find_many() got an unexpected keyword argument 'orderBy'. Did you mean 'order'?

```

Should we update some dependencies as well?

**Comment by jmorenoc-o** [comment]
Same for me. @mknet3 / @ishaan-jaff 

Since this issue is already closed I open a new issue https://github.com/BerriAI/litellm/issues/11086

Using `ghcr.io/berriai/litellm-database:main-v1.70.4-nightly`

Apparently the change has only been applied to the files in the path `/app/enterprise/litellm_enterprise/`

But the files in the path `/usr/lib/python3.13/site-packages/litellm_enterprise/...` still use `orderBy`

```
bash-5.2# grep -Ri "order={" /app/enterprise/litellm_enterprise/enterprise_callbacks/send_emails
/app/enterprise/litellm_enterprise/enterprise_callbacks/send_emails/base_email.py:            order={"created_at": "desc"}

bash-5.2# grep -Ri "orderBy={" /usr/lib/python3.13/site-packages/litellm_enterprise/enterprise_callbacks/send_emails
/usr/lib/python3.13/site-packages/litellm_enterprise/enterprise_callbacks/send_emails/base_email.py:            orderBy={"created_at": "desc"}
```
