### ISSUE TITLE
[Bug]: LiteLLM Prisma Client Exception - update spend logs: '<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by sp-aaflalo** [BerriAI/litellm#16366]
### What happened?

```
Alert type: db_exceptions
Level: High
Timestamp: 18:27:54Message: DB read/write call failed: '<' not supported between instances of 'NoneType' and 'str'[Non-Blocking]LiteLLM Prisma Client Exception - update spend logs: '<' not supported between instances of 'NoneType' and 'str'
Traceback (most recent call last):
  File "/app/litellm/proxy/db/db_spend_update_writer.py", line 988, in _update_daily_spend
    sorted(
    ~~~~~~^
        daily_spend_transactions.items(),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<14 lines>...
        ),
        ^^
    )[:BATCH_SIZE]
    ^
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

### Relevant log output

```shell

```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.79.0

**Comment by AlexsanderHamir** [comment]
Yes, the [PR](https://github.com/BerriAI/litellm/pull/16245) with the fix has been merged.

**Comment by ShawInnes** [comment]
I'm still experiencing this bug.  I'm running litellm/litellm:v1.80.5-nightly which I believe should contain the fix.
