### ISSUE TITLE
[Bug]: langfuse prompt throw error with the prompt name having "/"

### ISSUE THREAD

**Issue by sbbfung** [BerriAI/litellm#17565]
### What happened?

http://mylitellm.com/v1/chat/completions
```
{
    "model": "langfuse/model-from-prompt",
    "messages": [],
    "prompt_label": "production",
    "prompt_id": "ai_agent/faq",
    "prompt_variables": {
        "resources": "What is the capital of UK?"
    }
}
```
it response
```
{
    "error": {
        "message": "status_code: 404, body: <!DOCTYPE html><html lang=\"en\"><head><meta charSet=\"utf-8\" data-next-head=\"\"/><meta name=\"viewport\" content=\"width=device-width\" data-next-head=\"\"/><link rel=\"preload\" href=\"/_next/static/css/50c56d353b3316eb.css\" as=\"style\"/><link rel=\"stylesheet\" href=\"/_next/static/css/50c56d353b3316eb.css\" data-n-g=\"\"/><noscript data-n-css=\"\"></noscript><script defer=\"\" noModule=\"\" src=\"/_next/static/chunks/polyfills-42372ed130431b0a.js\"></script><script src=\"/_next/static/chunks/webpack-08671ee4eea221b0.js\" defer=\"\"></script><script src=\"/_next/static/chunks/framework-4184248f77e2870a.js\" defer=\"\"></script><script src=\"/_next/static/chunks/main-d727077fda814e25.js\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/_app-269babb8a3f0665e.js\" defer=\"\"></script><script src=\"/_next/static/chunks/pages/_error-5c17987bd0c211fc.js\" defer=\"\"></script><script src=\"/_next/static/Bvz1luLGpvZaS6V7RTwV5/_buildManifest.js\" defer=\"\"></script><script src=\"/_next/static/Bvz1luLGpvZaS6V7RTwV5/_ssgManifest.js\" defer=\"\"></script></head><body><link rel=\"preload\" as=\"image\" href=\"/icon.svg\"/><div id=\"__next\"><script>((e,i,s,u,m,a,l,h)=>{let d=document.documentElement,w=[\"light\",\"dark\"];function p(n){(Array.isArray(e)?e:[e]).forEach(y=>{let k=y===\"class\",S=k&&a?m.map(f=>a[f]||f):m;k?(d.classList.remove(...S),d.classList.add(a&&a[n]?a[n]:n)):d.setAttribute(y,n)}),R(n)}function R(n){h&&w.includes(n)&&(d.style.colorScheme=n)}function c(){return window.matchMedia(\"(prefers-color-scheme: dark)\").matches?\"dark\":\"light\"}if(u)p(u);else try{let n=localStorage.getItem(i)||s,y=l&&n===\"system\"?c():n;p(y)}catch(n){}})(\"class\",\"theme\",\"system\",null,[\"light\",\"dark\"],null,true,true)</script><div class=\"flex min-h-full flex-1 flex-col justify-center py-12 sm:px-6 lg:px-8\" data-sentry-component=\"Spinner\" data-sentry-source-file=\"spinner.tsx\"><div class=\"sm:mx-auto sm:w-full sm:max-w-md\"><img src=\"/icon.svg\" width=\"42\" height=\"42\" alt=\"Langfuse Icon\" class=\"mx-auto motion-safe:animate-spin\" data-sentry-component=\"LangfuseIcon\" data-sentry-source-file=\"LangfuseLogo.tsx\"/><h2 class=\"mt-5 text-center text-2xl font-bold leading-9 tracking-tight text-primary\">Loading<!-- --> ...</h2></div></div></div><script id=\"__NEXT_DATA__\" type=\"application/json\">{\"props\":{\"pageProps\":{\"statusCode\":404}},\"page\":\"/_error\",\"query\":{},\"buildId\":\"Bvz1luLGpvZaS6V7RTwV5\",\"nextExport\":true,\"isFallback\":false,\"gip\":true,\"locale\":\"en\",\"locales\":[\"en\"],\"defaultLocale\":\"en\",\"scriptLoader\":[]}</script><script>(function(){function c(){var b=a.contentDocument||a.contentWindow.document;if(b){var d=b.createElement('script');d.innerHTML=\"window.__CF$cv$params={r:'9a9501889b246047',t:'MTc2NDk1MzA0Mw=='};var a=document.createElement('script');a.src='/cdn-cgi/challenge-platform/scripts/jsd/main.js';document.getElementsByTagName('head')[0].appendChild(a);\";b.getElementsByTagName('head')[0].appendChild(d)}}if(document.body){var a=document.createElement('iframe');a.height=1;a.width=1;a.style.position='absolute';a.style.top=0;a.style.left=0;a.style.border='none';a.style.visibility='hidden';document.body.appendChild(a);if('loading'!==document.readyState)c();else if(window.addEventListener)document.addEventListener('DOMContentLoaded',c);else{var e=document.onreadystatechange||function(){};document.onreadystatechange=function(b){e(b);'loading'!==document.readyState&&(document.onreadystatechange=e,c())}}}})();</script></body></html>",
        "type": "None",
        "param": "None",
        "code": "404"
    }
}
```

I believe this is due to the error where the litellm accessing
`mylangfuse.com/api/public/v2/prompts/ai_agent/faq`
not
`mylangfuse.com/api/public/v2/prompts/ai_agent%2Ffaq`

I believe it can be fix base on https://github.com/langfuse/langfuse/issues/8006 
by change the file
litellm/integrations/langfuse/langfuse_prompt_management.py
at line 140
```
prompt_client = langfuse_client.get_prompt(
    langfuse_prompt_id, label=prompt_label, version=prompt_version
)
```
to
```
prompt_client = langfuse_client.client.prompts.get(
    urllib.parse.quote(langfuse_prompt_id, safe=""), label=prompt_label, version=prompt_version
)
```
from my testing on langfuse connection, it works with the `langfuse_client.client.prompts.get` approach

### Relevant log output

```shell
as the error message above
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v.1.80.5

**Comment by sbbfung** [comment]
After investigating, I found that the issue is due to the Langfuse version. LiteLLM is currently using the Langfuse v2 Python SDK, but this issue was fixed in Langfuse v3. Are there any plans for the LiteLLM team to support the v3 Langfuse Python SDK?

**Comment by AustinOrphan** [comment]
Hit this too and went digging. Still repros on v1.83.10, and the pin/imports look the same on main, so it's not fixed.

The slash just isn't getting URL-encoded before the request reaches Langfuse. LiteLLM passes the prompt name straight through to the langfuse SDK's `get_prompt(name)` (in `langfuse_prompt_management.py`, `_get_prompt_from_id`). The v2 SDK does try to encode it, but `_url_encode` in `langfuse/client.py` calls `urllib.parse.quote(url)` with the default `safe='/'`, so slashes survive:

```
>>> import urllib.parse
>>> urllib.parse.quote('ai_agent/faq')
'ai_agent/faq'
```

So the name goes out as two path segments and Langfuse 404s (that's the Next.js page in the original report). Every 2.x release does this, including the last one (2.60.10). Like sbbfung said above, v3 fixes it, it switched `_url_encode` to `quote(url, safe="")` and there's even a comment saying it's for prompt folders. But LiteLLM still pins `langfuse<3.0` and imports the v2-only `langfuse.client`, so that fix isn't reachable here.

One gotcha if anyone tries to work around it client-side: pre-encoding the name (`ai_agent%2Ffaq`) doesn't help either, the SDK re-quotes the `%` and you end up querying a literal `ai_agent%2Ffaq`.

So the fix is really on the LiteLLM side: either encode the name before handing it to the v2 SDK, or move the integration over to v3. Any chance this can be reopened? Folder names are pretty common and flat names are the only thing that works right now.
