### ISSUE TITLE
[Bug]: Cannot delete models in UI and APIs

### ISSUE THREAD

**Issue by anhphong22** [BerriAI/litellm#2951]
### What happened?

Cannot delete models even deleting them in postgres database.

## Request Feature
- Support delete models in UI

**Comment by ghost** [comment]
Hi @anhphong22 can you share the error you see? `/model/delete` works for me + in ci/cd testing 

<img width="949" alt="Screenshot 2024-04-11 at 5 39 41 AM" src="https://github.com/BerriAI/litellm/assets/17561003/dd77d920-9b30-4c71-8a0e-e9dd1ade6770">

**Comment by anhphong22** [comment]
> Hi @anhphong22 can you share the error you see? `/model/delete` works for me + in ci/cd testing
> 
> <img alt="Screenshot 2024-04-11 at 5 39 41 AM" width="949" src="https://private-user-images.githubusercontent.com/17561003/321632398-dd77d920-9b30-4c71-8a0e-e9dd1ade6770.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4OTA1NjYsIm5iZiI6MTcxMjg5MDI2NiwicGF0aCI6Ii8xNzU2MTAwMy8zMjE2MzIzOTgtZGQ3N2Q5MjAtOWIzMC00YzcxLThhMGUtZTlkZDFhZGU2NzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDAyNTEwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0Nzc3YWVlNjg5MjYwODY1NDBhM2QwMTZkMTMzY2NjNjg3MzI1OTI3NjZjMDgzYTQ2OTQ4M2E5YzI4ODc5MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i6K2rSoeOsf50w67lCoj3YZuUsq6YtMUjzc4H2qS8ic">

Yes. Although the request received 200 status code, I used GET to endpoints `/v1/model/info` remaining the model that had been deleted.

**Comment by ghost** [comment]
Hi @anhphong22 thanks for this, 
- Was the model created via `/model/new` ?
- If so, then does it show up after restarting the server?

**Comment by anhphong22** [comment]
Hi @krrishdholakia,
I will show you the way I did in 2 versions before `v1.34.31` and thereafter.
In the first version, I deployed services and updated all models to config.yaml file (deployed it in K8s and mounted to longhorn to keep all models after restarting the server), which worked well.
In the current version `v1.35.1`, I have stored all models in postgres db (configured env `STORE_MODEL_IN_DB = 'True'`). That is ok when storing models to database, but it raised a bug when deleting models (using openapi swagger, 😁 I am so happy if you can support delete models in UI). I deleted rows in postgres forcefully, but I returned UI that everything is showed up in UI (cached data?). If so, I believe that using cron job to check the changes in db is the better option than that of caching data to server. This is a high priority bug I think.

**Comment by anhphong22** [comment]
I found a new bug 
![image](https://github.com/BerriAI/litellm/assets/74782468/b71f48b6-ac88-49a8-a869-0ee4c169e2be)

I migrated from version `v.1.34.38`

**Comment by ncecere** [comment]
I am also running into this issue.  I spun up a new instance using version [v1.35.4] and still have this issue.  my process is.

1. add model via api (/model/new)
2. verify it's working
3. delete model via api (/model/delete)

model is still available via (/model/info) and in the UI.  I have restarted the server and it is still there.  I also get the sam issue if I perform all of these action via the web UI

**Comment by ghost** [comment]
Hey @ncecere @anhphong22 thanks for this - acknowledging the issue. 

Will have a fix out for this by tonight/early tomorrow. 


Would love to setup a direct support channel for y'all.

Here's my linkedin: 
- https://www.linkedin.com/in/krish-d/

Here's our discord: 
- https://discord.gg/wuPM9dRgDw

**Comment by ghost** [comment]
Picking this up today

**Comment by ghost** [comment]
This commit should fix the issue - https://github.com/BerriAI/litellm/commit/2d4fe072ad830400ccf356270c3fad1707620252

It checks the db + Config, and deletes any models in Router not present in the parent list. 

Added testing for this as well.

**Comment by ghost** [comment]
should be live soon in v`1.35.8`. 

@ncecere @anhphong22 closing for now. Please bump me if this isn't fixed.

**Comment by anhphong22** [comment]
Thanks @krrishdholakia I will test it.
