### ISSUE TITLE
[Bug]: Logs not always going to Langfuse default project, and sometimes wrong project completely

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4944]
### What happened?

I currently have this config, but it seems like when I use a key _without_ setting a team, nothing is sent to Langfuse. I was expecting that it would go to my default vars that were set like this:

```sh
export LANGFUSE_SECRET_KEY="sk-lf-1234567890abcdef"
export LANGFUSE_PUBLIC_KEY="pk-lf-1234567890abcdef"
export LANGFUSE_HOST="https://langfuse.example.com
```

```yaml
litellm_settings:
  drop_params: True
  redact_messages_in_exceptions: True
  cache: True
  cache_params:
    type: s3
    s3_bucket_name: os.environ/CACHING_S3_BUCKET_NAME
    s3_region_name: os.environ/CACHING_AWS_DEFAULT_REGION
    s3_aws_access_key_id: os.environ/CACHING_AWS_ACCESS_KEY_ID
    s3_aws_secret_access_key: os.environ/CACHING_AWS_SECRET_ACCESS_KEY
    s3_endpoint_url: os.environ/CACHING_AWS_ENDPOINT_URL_S3
  failure_callback: ["sentry", "langfuse"]
  num_retries: 0
  allowed_fails: 2
  request_timeout: 3600
  success_callback: ["langfuse", "s3"]
  s3_callback_params:
    s3_bucket_name: os.environ/LOGGING_S3_BUCKET_NAME
    s3_region_name: os.environ/LOGGING_AWS_DEFAULT_REGION
    s3_aws_access_key_id: os.environ/LOGGING_AWS_ACCESS_KEY_ID
    s3_aws_secret_access_key: os.environ/LOGGING_AWS_SECRET_ACCESS_KEY
    s3_endpoint_url: os.environ/LOGGING_AWS_ENDPOINT_URL_S3
  default_team_settings:
    - team_id: example_team
      success_callback: ["langfuse", "s3"]
      langfuse_secret: os.environ/LANGFUSE_PRIVATE_KEY_EXAMPLE
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY_EXAMPLE
```

The user key I created was done with:

```sh
curl -v -H "content-type: application/json" -H 'accept: application/json' -H 'Authorization: Bearer removed' 'https://litellm-epic-uk.a.run.app/key/generate' --data '{"key_alias": "example-worker"}' | jq
```

```json
{
  "models": [],
  "spend": 0.0,
  "max_budget": null,
  "user_id": null,
  "team_id": null,
  "max_parallel_requests": null,
  "metadata": {},
  "tpm_limit": null,
  "rpm_limit": null,
  "budget_duration": null,
  "allowed_cache_controls": [],
  "soft_budget": null,
  "key_alias": "example-worker",
  "duration": null,
  "aliases": {},
  "config": {},
  "permissions": {},
  "model_max_budget": {},
  "send_invite_email": null,
  "key": "sk-REMOVED",
  "key_name": "sk-...VED",
  "expires": null,
  "token_id": "REMOVED"
}
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by Manouchehri** [comment]
Sometimes logs go correctly to the default project.

<img width="583" alt="image" src="https://github.com/user-attachments/assets/57eba059-e0a1-4ff6-a64c-b15f6c2f11ba">


Other times, LiteLLM sends logs to a _completely_ unrelated different Langfuse project. This is **really** bad.

<img width="631" alt="image" src="https://github.com/user-attachments/assets/f4398c81-8427-4777-984b-131c42db5a41">

It seems like there's something sticky going on. (This is **really** _really_ bad, since it breaks the permission separation we have on different Langfuse projects.)

**Comment by Manouchehri** [comment]
Yikes. It's flooding random projects. None of these requests should be going to this project.

<img width="591" alt="image" src="https://github.com/user-attachments/assets/30825407-8b45-4687-b758-23b2fa24c7a3">

**Comment by ghost** [comment]
Hi @Manouchehri i believe this might've been caused by how the langfuse client was being initialized. 

Fixed here - https://github.com/BerriAI/litellm/pull/5618/commits/46be005e67e54a9678606b07a95e4ef4527e1b08

**Comment by Manouchehri** [comment]
This is still happening to me: logs that should be going to the default project, sometimes randomly go to the last used Langfuse project.

**Comment by ghost** [comment]
@Manouchehri do you have a repro for this? I don't see this anymore. 

Especially after we fixed the client re-init logic - https://github.com/BerriAI/litellm/pull/5618/files#diff-202545f3ab4f290ac9967d9ba19689aafe15902296a2ef5a6ca5410a93eaa38bR927

**Comment by ghost** [comment]
@Manouchehri do you still see this? if so, can you share a way to repro this issue on main latest 

if not, can we please close this
