### ISSUE TITLE
[Bug]: entrypoint.sh move, causing cloud run builds to fail

### ISSUE THREAD

**Issue by tb-config-manager** [BerriAI/litellm#6261]
### What happened?

I think #6110 breaks the example Dockerfile for Cloud Run: https://github.com/BerriAI/example_litellm_gcp_cloud_run

As most people have just forked this and are using it, you may want to fix it. As a novice, I couldn't fix it myself. What should the new Dockerfile be?

![CleanShot 2024-10-16 at 14 13 25@2x](https://github.com/user-attachments/assets/e30cbdfc-a107-455c-8051-367d034db209)
![CleanShot 2024-10-16 at 14 14 05@2x](https://github.com/user-attachments/assets/d975eac7-b427-40ab-97eb-01f4ca887eb6)

**Comment by ghost** [comment]
Fixed - https://github.com/BerriAI/example_litellm_gcp_cloud_run/commits/main/Dockerfile

Let me know if that solves it @tb-config-manager

**Comment by tb-config-manager** [comment]
Unfortunately, problem still continues:

![CleanShot 2024-10-16 at 20 20 24@2x](https://github.com/user-attachments/assets/1ff1a150-e0b5-412b-af82-1243be0719e5)
![CleanShot 2024-10-16 at 20 21 01@2x](https://github.com/user-attachments/assets/aad6276a-55bd-4796-b87d-5ffe84394e07)

**Comment by tb-config-manager** [comment]
You may want to re-open this @krrishdholakia

**Comment by ghost** [comment]
Hi @tb-config-manager the error doesn't show any docker build issue 

it's saying the docker failed to start, but i can't tell what the cause was, can you share the full log? looking for something similar to what you shared initially

**Comment by tb-config-manager** [comment]
Hey, I think this information may help you - I have not changed anything on config but seems like something broke port configuration. Here is a soundless video to show logs:

https://github.com/user-attachments/assets/bd8dbfd7-7d55-4f7a-bcea-5d9935562f82

**Comment by tb-config-manager** [comment]
Let me know if you need more info or jump to call @krrishdholakia

**Comment by ghost** [comment]
I don't see any logs related to the litellm build step @tb-config-manager 

I can see you're using a custom docker image, are you unable to use our official release? we support gcs bucket based config.yaml as well - https://docs.litellm.ai/docs/proxy/deploy#4-providing-litellm-configyaml-file-as-a-s3-gcs-bucket-objecturl

**Comment by tb-config-manager** [comment]
Oh, it was my mistake, finally I get the better video:

https://github.com/user-attachments/assets/7d4f3666-41bc-46ec-b0a9-74afddb66215

Will use config.yaml on s3 - thanks!

**Comment by tb-config-manager** [comment]
Actually I only use this config:

```
# Use the provided base image
FROM ghcr.io/berriai/litellm:main-latest

# Set the working directory to /app
WORKDIR /app

# Copy the configuration file into the container at /app
COPY litellm_config.yaml .

# Expose the necessary port
EXPOSE 4000/tcp

CMD ["--port", "4000", "--config", "litellm_config.yaml"]
```

Just have litellm_config.yaml next to it as you have shown in example.

**Comment by ghost** [comment]
Scroll down - i can't see the container logs 
<img width="367" alt="Screenshot 2024-10-17 at 11 07 00 AM" src="https://github.com/user-attachments/assets/81048d2a-daaa-41b4-aa93-f4f800affdb8">

**Comment by tb-config-manager** [comment]
It is my msitake I guess, the new instance works perfectly fine!

**Comment by ishaan-jaff** [comment]
Hi @tb-config-manager , thanks for using LiteLLM. Any chance we can hop on a call to learn how we can improve LiteLLM Proxy for you ? 

We’re planning roadmap and I’d love to get your feedback 

my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
