### ISSUE TITLE
[Bug]: Error on Python 3.13 due to "re.T"

### ISSUE THREAD

**Issue by iwamot** [BerriAI/litellm#7306]
### What happened?

Starting with Python 3.13, `re.T` has been removed, causing errors in the following locations:

- `litellm/integrations/azure_storage/azure_storage.py`, line 6: `from re import S, T`
- `tests/llm_translation/test_anthropic_text_completion.py`, line 3: `from re import T`

Please consider removing or replacing `re.T`.

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.55.4

### Twitter / LinkedIn details

@iwamot / https://www.linkedin.com/in/iwamot/

**Comment by danielsiwiec** [comment]
same issue here after upgrading from `1.55.3` to `1.55.6`

**Comment by ishaan-jaff** [comment]
investigating and working on a fix

**Comment by ishaan-jaff** [comment]
fixed here: https://github.com/BerriAI/litellm/pull/7314/ 

Also made the following improvements:
- Added a test to ensure litellm works on python 3.13 
- Added ruff rule to prevent unused imports https://github.com/BerriAI/litellm/pull/7313

cc @danielsiwiec @iwamot

**Comment by krik8235** [comment]
I guess this suggestion is not reflected in the latest version of 1.55.7?
I still see `from re import S, T` on `litellm/integrations/azure_storage/azure_storage.py` - which raise the error

**Comment by ishaan-jaff** [comment]
1.55.7 is not out as yet @krik8235

**Comment by danielsiwiec** [comment]
I'll give this a try later today/tomorrow

**Comment by krik8235** [comment]
@danielsiwiec - worked perfectly with 1.55.8. thanks
