### ISSUE TITLE
[Bug]: Redis Cache in cluster mode doesn't work in litellm router

### ISSUE THREAD

**Issue by ogunoz** [BerriAI/litellm#8760]
### What happened?

Getting cached response doesn't work starting 1.61.11 version. Relevant logs are shared below.

I noticed that writing caches work without any error (And I can see respective log on our Redis), but fetching them back throws errors. I tried with 1.61.13 as well but nothing changed. Meanwhile we pinned to the 1.61.9 version which seems working.

### Relevant log output

```shell
Error occurred in async batch get cache - Event loop is closed

Error occurred in async batch get cache - CROSSSLOT Keys in request don't hash to the same slot
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

1.61.11

**Comment by ishaan-jaff** [comment]
hi @ogunoz is this calling a RedisCluster ?

**Comment by ishaan-jaff** [comment]
should be working here: https://github.com/BerriAI/litellm/releases/tag/v1.61.13.rc

**Comment by ogunoz** [comment]
Hey @ishaan-jaff thank you for your answer. It is a RedisCluster yes.

I still have the error even with 1.61.15. By the way we are not using Litellm as Proxy server, we are using the Python SDK

**Comment by ogunoz** [comment]
Hmm even though i still get the error logs, i am also getting the response from logs actually, so it seems like less critical

**Comment by ogunoz** [comment]
I can verify that SET and GET calls to redis cluster works as expected that is why actual prompt caching works as expected. Issue is with MGET calls

[https://stackoverflow.com/a/79455860](https://stackoverflow.com/a/79455860)

I found few logs from Redis cluster if it gives some insight @ishaan-jaff 

```
MGET litellm:deployment:e35983666a577e9054ac068971f5c34d05ccc4ad9e1d4902df1912d360da72f5:cooldown 
litellm:deployment:85af94d8352f857079a9956535d0f4ba3dee6fbe7c6eb8a51f8f7596d89323d6:cooldown 
litellm:deployment:c5f312129dbb3c7e2d31371b0f9af3ae9756407e8d430ad671e90a1072178238:cooldown 
litellm:deployment:9bb5fe5b696f042c7f1f58608305e9dc233c25da11c6b74a28d70cb1d1bc86be:cooldown 
litellm:deployment:9bc88229eb670446f9a739bf0c4f9685a27f4e200f96598ef6e7e1ffed64bc9d:cooldown 
litellm:deployment:42ad7471ca7517557ffc48e0c9fab0d48988076274a4485dd50f4ab32e2d811e:cooldown 
litellm:deployment:0594db3bc1ee7bf62a2c3355c000099979d165eee93fd7b279962bab5a47a6f9:cooldown
```

**Comment by ogunoz** [comment]
According to https://repost.aws/knowledge-center/elasticache-crossslot-keys-error-redis 

It is possible to ensure that keys are in the same MGET call will be in the same slot by setting { } characters to the common part, therefore it seems like setting that in `get_cooldown_cache_key` solves the issue. There are hardcoded cooldown cache keys in the same module, i also assume that we use the same function everywhere there (`cooldown_cache.py`)

```python
    @staticmethod
    def get_cooldown_cache_key(model_id: str) -> str:
        # Notice the { } chars
        return f"{{deployment}}:{model_id}:cooldown"
```

**Comment by ishaan-jaff** [comment]
For Redis cluster we don't use mget we use mget atomic

**Comment by ogunoz** [comment]
Ah thank you so much @ishaan-jaff for your answer. I found that once we can use `RedisClusterCache` properly, there is no such issue. However in `router.py` even though `startup_nodes` are provided in `cache_kwargs` always `RedisCache` instance created. Therefore it opts for mget instead of mget-nonatomic. Could you make a change there (`litellm.router.py` line `350`)


Even though RedisCache class instantiates all the redis clients (sync and async) as cluster instances (thanks to redis kwargs), it goes to MGET instead of mget-nonatomic.
From
```python
redis_cache = RedisCache(**cache_config)
```

To 
```python
if cache_config.get("startup_nodes"):  # or "startup_nodes" in cache_config
    redis_cache = RedisClusterCache(**cache_config)
 else:
    redis_cache = RedisCache(**cache_config)
```

**Comment by ogunoz** [comment]
My attempt to fix it :) https://github.com/BerriAI/litellm/pull/9010

**Comment by ogunoz** [comment]
Closing the issue, fixed in 1.63.3
